version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    labels:
      - "area: dependencies"
      - "semver: patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "alexrashed"
    labels:
      - "area: dependencies"
      - "semver: patch"
