sudo: required

language: python

services:
  - docker

python:
  - "3.6"

branches:
  only:
    - master

before_install:
  - "sudo apt-get purge openjdk-6*"
  - "sudo apt-get purge openjdk-7*"
  - "sudo apt-get purge oracle-java7-*"
  - "sudo apt-get purge python2.7"
  - "nvm install 6; nvm alias default node"
  - "sudo useradd localstack -s /bin/bash"

addons:
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    - AWS_DEFAULT_REGION=us-east-1

install:
  - make reinstall-p3
  - make init

script:
  - set -e # fail fast
  - DEBUG=1 LAMBDA_EXECUTOR=docker make test
  - LAMBDA_EXECUTOR=local USE_SSL=1 make test
  - make docker-build
  - make docker-push-master

after_success:  
  - make coveralls

notifications:
  email: false
