language: python
dist: xenial
python:
  - "3.7"

services:
  - docker

branches:
  only:
    - master

addons:
  apt:
    packages:
      - openjdk-8-jre-headless

before_install:
  - "sudo apt-get purge openjdk-6*"
  - "sudo apt-get purge openjdk-7*"
  - "sudo apt-get purge oracle-java7-*"
  - "sudo apt-get purge python2.7"
  - "nvm install 6; nvm alias default node"
  - "sudo useradd localstack -s /bin/bash"

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - BOTO_CONFIG=/dev/null

install:
  - set -e
  - # install under python 3
  - PIP_CMD=pip3 VENV_OPTS="-p '`which python3`'" make install-basic
  - make init
  - make prepare-java-tests-if-changed
  - nohup docker pull lambci/lambda:nodejs8.10 > /dev/null &
  - nohup docker pull lambci/lambda:ruby2.5 > /dev/null &
  - nohup docker pull lambci/lambda:python3.6 > /dev/null &
  - nohup docker pull lambci/lambda:dotnetcore2.0 > /dev/null &
  - nohup docker pull lambci/lambda:java8 > /dev/null &

script:
  - set -e # fail fast
  # run tests using Python 3
  - DEBUG=1 LAMBDA_EXECUTOR=docker USE_SSL=1 TEST_ERROR_INJECTION=1 make test
  # run tests using Python 2
  #   Note: we're not using multiple versions in the top-level "python" configuration,
  #   but instead reinstall using 2.x here, as that allows us to re-use some cached libs etc.
  - "make reinstall-p2 > /dev/null"
  - make init
  - LAMBDA_EXECUTOR=docker-reuse TEST_PATH="tests/integration/test_lambda.py tests/integration/test_integration.py" make test
  # build Docker image
  - make docker-build
  # run Java tests
  # TODO: re-enable java tests when fixed!
  # - make test-java-if-changed; true
  # push Docker image (if on master branch)
  - make docker-push-master

after_success:
  - make coveralls || true

notifications:
  email: false
