# Bitbucket Pipelines build configuration for LocalStack

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - sudo useradd localstack -s /bin/bash
          - sudo apt-get install -y zip python3-pip python-virtualenv && make reinstall-p3
          - HOSTNAME=localhost LAMBDA_EXECUTOR=local make test
          - make docker-build
          - make docker-push-master
