blank_issues_enabled: true
contact_links:
  - name: ðŸ“–  LocalStack Documentation
    url: https://localstack.cloud/docs/getting-started/overview/
    about: The LocalStack documentation may answer your questions!
  - name: ðŸ’¬  LocalStack Community Support (Slack)
    url: https://localstack.cloud/slack
    about: Please ask and answer questions here.
