blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Feature request
    url: https://discuss.localstack.cloud/
  - name: â“ Question
    url: https://discuss.localstack.cloud
    about: Ask a question about LocalStack
  - name: ğŸ“–  LocalStack Documentation
    url: https://localstack.cloud/docs/getting-started/overview/
    about: The LocalStack documentation may answer your questions!
  - name: ğŸ’¬  LocalStack Community Support (Slack)
    url: https://localstack-community.slack.com
    about: Please ask and answer questions here.
