name: Enforce Labels
on:
  pull_request_target:
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  labels:
    uses: localstack/meta/.github/workflows/pr-enforce-labels.yml@main
    secrets:
      github-token: ${{ secrets.PRO_ACCESS_TOKEN }}
