name: smoke-tests-against-redhat
on:
  schedule:
    - cron: '0 7 * * 1'  # every Monday morning
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-redhat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Open Source
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build RH Docker Image
        run: |
          docker build  -t localstack-redhat -f ./Dockerfile.rh \
            --build-arg LOCALSTACK_BUILD_GIT_HASH=$(shell git rev-parse --short HEAD) \
            --build-arg=LOCALSTACK_BUILD_DATE=$(shell date -u +"%Y-%m-%d") \
            .

      - name: Execute Smoke Tests
        env:
          TEST_LOCALSTACK_API_KEY: ${{ secrets.TEST_LOCALSTACK_API_KEY }}
        run: |
          CI_SMOKE_IMAGE_NAME="localstack-redhat" make ci-pro-smoke-tests
