name: Sync Project Cards

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  sync-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Project status change necessary?
        uses: actions/github-script@v6
        id: determine-status
        with:
          result-encoding: string
          script: |
            // Get the labels on the issue
            const listLabelsOnIssueResponse = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const issueLabels = listLabelsOnIssueResponse.data.map(e => e.name);

            // define the mapping
            // the order is important, the further down the more important (if multiple status labels are set)
            const mapping = {
                "status: triage needed": "status: triage needed â“",
                "status: backlog": "status: backlog ğŸ—ƒ",
                "status: confirmed": "status: backlog ğŸ—ƒ",
                "status: accepted": "status: backlog ğŸ—ƒ",
                "status: stale": "status: stale ğŸ˜´",
                "status: response required": "status: response required ğŸ—¨",
                "status: in progress": "status: in progress ğŸ§‘â€ğŸ’»",
                "status: resolved/stale": "status: stale ğŸ˜´",
                "status: resolved/fixed": "status: closed âœ”",
                "status: resolved/workaround": "status: closed âœ”"
            };

            // apply the most important mapped project status
            let result = false;
            for (const label in mapping) {
              if (issueLabels.includes(label)) {
                result = mapping[label];
              }
            }

            // if none was found (no known status label is set on the issue), use the fallback (triaging)
            if (result == false) {
              result = "status: triage needed â“";
            }

            // return the result - usable as "steps.<step-id>.outputs.result" by other steps
            return result;

      - name: Sync Card Status
        if: ${{steps.determine-status.outputs.result}}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ secrets.PRO_ACCESS_TOKEN }}
          organization: ${{ github.repository_owner }}
          project_id: 17
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{steps.determine-status.outputs.result}}
